lunasoul/base/urls.py
from django.urls import path, include
from . import views

app_name = 'base'

urlpatterns = [
    path('', views.index, name='index'),
]

lunasoul/blog/urls.py
from django.views.generic import ListView, DetailView
from .models import Post
from django.urls import path, include
from . import views

from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:pk>/', views.post_detail, name='post_detail'),
]

lunasoul/lunasoul/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', include('base.urls')),
    path('registration/', include('registration.urls')),
    path('merch/', include('merch.urls'))
] #+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lunasoul/merch/urls.py
from django.urls import path, include
from . import views
from django.shortcuts import render

app_name = 'merch'

urlpatterns = [
    path('', views.shop, name='shop'),
]

lunasoul/registration/urls.py
from . import views
from django.urls import path
from registration.views import register

app_name = 'registration'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
]

lunasoul/base/models.py
from django.db import models

# Create your models here.

lunasoul/blog/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

lunasoul/merch/models.py
from django.db import models

# Create your models here.

lunasoul/base/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    """
    Renders the 'index.html' template.

    Args:
        request (HttpRequest): The HTTP request object.

    Returns:
        HttpResponse: A rendered HTTP response.

    """
    return render(request, 'index.html')

lunasoul/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

def post_list(request):
    posts = Post.objects.all()
    return render(request, 'blog/post_list.html', {'posts': posts})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})

lunasoul/merch/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def shop(request):
    """
    Renders the 'shop.html' template if the user is logged in.

    Args:
        request (HttpRequest): The HTTP request object.

    Returns:
        HttpResponse: A rendered HTTP response.

    """
    return render(request, 'shop.html')

lunasoul/base/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>LUNA SEOUL</title>
</head>
<body>
{% include 'navigation.html' %}

  <!-- Welcome Banner -->
  <header class="jumbotron text-center">
    <div class="container">
      <h1>LUNA SOUL</h1>
        <br>
      <p style="font-size: 40px;">Our sophomore album <span style="font-weight: bold; color: #d2184e;">HOT PINK</span> drops May 1st<p>
    </div>
  </header>

  <!-- Band Picture section -->
  <section class="container text-center">
    <img src="https://wildezine.com/wp-content/uploads/2022/05/Screen-Shot-2022-05-19-at-1.26.19-PM-900x604.png" alt="Band Image" class="img-fluid rounded-circle">
  </section>

  <!-- About section -->
  <section class="container">
    <h2>About Us</h2>
   <p>We are Korea's next hot hot hot girl group, LUNA SOUL. Our journey began when we auditioned for the TV talent contest Superstar-K.<p/>
    <p>It was so nerve wracking sitting back stage hearing everyone with such awesome voices. As the competition went on we got to know each other and really support each others journey.</p>
    <p>When the judges suggest we get put in a group it was like obviously, why didn't we think of that. It was just the natural thing to do.</p>
    <p>We are like best friends now and it's so much fun getting to travel the world together and do what we love. Come see us on tour, and tweet us which city we should visit next!</p>
    <p>XOXO LUNA SOUL</p>

    <!-- Music section -->
  <section class="container">
    <h2>Our Music</h2>
      <p>We want our sound to be like pink and glittery with cool hip hop and punky vibes. Like we just want it to feel really girly but also tough and with an attitude.<p/>
      <p>So far we have released the album <span style="font-weight: bold; text-size: 60px; color: #0d755b">Sexy Babies</span> which went double platinum.</p>
      <p>Our next album,  <span style="font-weight: bold; color: #d2184e;">HOT PINK</span>, is out May 1st. You can preorder it where-ever music is sold.</p>

lunasoul/base/templates/navigation.html
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <style>
    @import url("https://fonts.googleapis.com/css2?family=Lilita+One&display=swap");
    @import url("https://fonts.googleapis.com/css2?family=Karla:wght@200&display=swap");

    body {
      background-color: #f0e6fc;
    }

    .navbar {
      background-color: #5c18d2;
    }

    h1 {
    font-family: "Lilita One", cursive;
    font-size: 100px;
    color: #5c18d2;
    text-shadow: 2px 2px 4px #f5c7d1;
    }

    h2, h3 {
      font-family: 'Karla', ExtraBold 800;
      font-size: 60px;
      color: #5c18d2;
    }

    .jumbotron {
      background-color: #d7caed;
    }

    .card {
      background-color: #d7caed;
    }

    .btn-primary {
      background-color: #bea1f0;
      border-color: #f5c7d1;
    }

    .btn-primary:hover {
      background-color: #5c18d2;
      border-color: #ad1444;
    }

    p {
      font-family: 'Karla', sans-serif;
      font-size: 30px;
    }
  </style>

<!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'base:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:post_list' %}">Blog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'registration:register' %}">Join</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'merch:shop' %}">Merch (MEMBER ACCESS ONLY)</a>
        </li>
      </ul>
    </div>
  </nav>

lunasoul/blog/templates/blog/navigation.html
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <style>
    @import url("https://fonts.googleapis.com/css2?family=Lilita+One&display=swap");
    @import url("https://fonts.googleapis.com/css2?family=Karla:wght@200&display=swap");

    body {
      background-color: #f8e9ed;
    }

    .navbar {
      background-color: #d2184e;
    }

    h1 {
    font-family: "Lilita One", cursive;
    font-size: 100px;
    color: #d2184e;
    text-shadow: 2px 2px 4px #f5c7d1;
    }

    h2, h3 {
      font-family: 'Karla', ExtraBold 800;
      font-size: 60px;
      color: #d2184e;
    }

    .jumbotron {
      background-color: #ffd7e5;
    }

    .card {
      background-color: #ffeff3;
    }

    .btn-primary {
      background-color: #d2184e;
      border-color: #d2184e;
    }

    .btn-primary:hover {
      background-color: #ad1444;
      border-color: #ad1444;
    }

    p {
      font-family: 'Karla', sans-serif;
      font-size: 30px;
    }
  </style>
<!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'base:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:post_list' %}">Blog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'registration:register' %}">Join</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'merch:shop' %}">Merch (MEMBER ACCESS ONLY)</a>
        </li>
      </ul>
    </div>
  </nav>

lunasoul/blog/templates/blog/post_detail.html
{% include 'navigation.html' %}
<h2 style="color: cornflowerblue; font-family: 'Karla', cursive; font-size: 80px; font-weight: bold;">{{ post.title }}</h2>
<p>{{ post.content }}</p>
<h2 style="color: cornflowerblue; font-family: 'Karla', cursive; font-size: 50px; font-weight: bold; text-align: center;">XOXO LUNA SOUL</h2>                                         XOXO LUNA SOUL</h2>
<p>Created at: {{ post.created_at }}</p>

lunasoul/blog/templates/blog/post_list.html
{% include 'navigation.html' %}
<h1>Blog Posts</h1>
{% for post in posts %}
    <p style="color: cornflowerblue; font-family: 'Karla', cursive; font-size: 50px; font-weight: bold;"><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></p>
    <p>Created at: {{ post.created_at }}</p>
    <br>
{% endfor %}

lunasoul/merch/templates/navigation.html
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <style>
    @import url("https://fonts.googleapis.com/css2?family=Lilita+One&display=swap");
    @import url("https://fonts.googleapis.com/css2?family=Karla:wght@200&display=swap");

    body {
      background-color: #f8e9ed;
    }

    .navbar {
      background-color: #d2184e;
    }

    h1 {
    font-family: "Lilita One", cursive;
    font-size: 100px;
    color: #d2184e;
    text-shadow: 2px 2px 4px #f5c7d1;
    }

    h2, h3 {
      font-family: 'Karla', ExtraBold 800;
      font-size: 60px;
      color: #d2184e;
    }

    .jumbotron {
      background-color: #ffd7e5;
    }

    .card {
      background-color: #ffeff3;
    }

    .btn-primary {
      background-color: #d2184e;
      border-color: #d2184e;
    }

    .btn-primary:hover {
      background-color: #ad1444;
      border-color: #ad1444;
    }

    p {
      font-family: 'Karla', sans-serif;
      font-size: 30px;
    }
  </style>
<!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'base:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:post_list' %}">Blog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'registration:register' %}">Join</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'merch:shop' %}">Merch (MEMBER ACCESS ONLY)</a>
        </li>
      </ul>
    </div>
  </nav>